### ISSUE TITLE
assert_set_eq does not work with HashSet

### ISSUE THREAD

**Issue by udalrich** [SixArm/assertables-rust-crate#1]
I was looking for something to check the contents of a `HashSet`, and `assert_set_eq` looked like exactly what I wanted.  However,

```
let s: HashSet<String> = ...;
assert_set_eq!(s, [])
```
checks compares the set, not its contents, to `[]`.

**Comment by joelparkerhenderson** [comment]
Yes and you're making a good point about the naming.

The function `assert_set_eq` is intended to compare two iterables, i.e. two things that implement `into_iter`, and to do it by using mathematical-set semantics, i.e. assert that the iterables contain the same items, ignoring any duplicates.

The macro implementation is similar to this:

```
x.into_iter().collect() == y.into_iter().collect()
```
                
A more-semantic function name could be an improvement. Perhaps something like `assert_as_into_iter_has_same_set_of_items` or some such?

For comparison, a HashSet is a collection akin to a wrapper.

If your goal is to assert that the HashSet is empty, then one way is to use `pub fn is_empty(&self) -> bool`.

If your goal is to assert that the HashSet contains specific items, then one way is to create another HashSet with the items that you care about, then use `pub fn eq(&self) -> bool` which compares the items a.k.a. one HashSet's values to the other HashSet's values.

You might also be interested in HashSet `union`, `superset`, `subset`, and similar functions that can be useful for comparing a HashSet's values with another HashSet's values.

Does this information address your need enough?

**Comment by joelparkerhenderson** [comment]
This is open for 2 weeks with no response, so I'm closing it for now. Feel free to re-open it if new information arrives.
