### ISSUE TITLE
More types of assertions?

### ISSUE THREAD

**Issue by drmorr0** [SixArm/assertables-rust-crate#4]
I am wondering if adding more types of assertions would be useful/beneficial to this project?  I would really like to have things like

```
assert_none!(option) // ensures the option type is empty
assert_some_eq!(option, val) // ensures the option is inhabited and contains val
assert_ok!(result) // ensures the result is OK
assert_err_is!(result, errtype) // ensures the result is the expected error
assert_len!(seq, n) // ensures the sequence or object has n elements
```

I'm happy to implement and submit a PR if this would be useful!

**Comment by joelparkerhenderson** [comment]
> I am wondering if adding more types of assertions would be useful/beneficial to this project?

Yes please.

> I would really like to have things like...

All sound good. For the naming, I suggest slightly-longer names to improve clarity. (It's one of the feedback areas coming from users of assertables).

So for example...

assert_len
assert_count

assert_option_some
assert_option_none

assert_result_ok
assert_result_err

assert_result_ok_eq (and _ne, _le, _lt, _gt, _ge)
assert_result_err_eq (and _ne, _le, _lt, _gt, _ge)

Heads up that the existing implementation macros are significantly long. Each macro group is its own file, and comes with typical cargo tests, and cargo doc comments that are tests, and corresponding links in the README. If the existing code is clear enough for you, that's excellent. Or if you want to ask questions and/or hop on a video call to discuss, that's good too. I very much appreciate your help!

**Comment by drmorr0** [comment]
I will take a stab and see what I can come up with.  I'll let you know if I run into issues!

**Comment by joelparkerhenderson** [comment]
Completed these:

* assert_ok etc.
* assert_err etc.
* assert_some etc.
* assert_none
* assert_ready etc.
* assert_pending

I have assert_len on the roadmap.

Thanks!

**Comment by dzmitry-lahoda** [comment]
inserting asset type is assert of number being within range, but less of other number:

```
assert_lt_by!(9,10,2); // success
assert_lt_by!(7,10,2); // panics
```

similar to check number withing some delta/epsilon, but directional.

usage of existing delta/epsilon requires manual calculation of midpoints which is a lot of noise.

**Comment by joelparkerhenderson** [comment]
Are you saying something like this?

```rust
assert_lt_by!(a, b, c) => (b - a) < c
```

**Comment by joelparkerhenderson** [comment]
Update for you: the feature is ready as non-check, and I intend to add the check this weekend.

**Comment by joelparkerhenderson** [comment]
Released. When convenient, can you upgrade to version 9.5.0, and try the new macros `assert_diff_eq_x` and `assert_abs_diff_eq_x` and let me know if they work the way you want?
