### ISSUE TITLE
Improved usage?

### ISSUE THREAD

**Issue by bjones1** [SixArm/assertables-rust-crate#6]
Thanks for creating this crate! These wide range of assertions have done a lot to help me clean up and simplify my code. I had one small problem/suggestion: I typically use the panic form of the assertion. To do so, I need to import both the panic form and the result form. For example:

``` Rust
use assertables::{assert_starts_with, assert_starts_with_as_result};

fn foo() {
    assert_starts_with!("Hot dog!", "Hot");
}
```

I'd like to only import the macro I need -- just `use assertables::assert_starts_with`. I prefer to avoid the vagueness and potential namespace pollution from `use assertables::*`. Is there some easy way to do this that I'm overlooking?

**Comment by joelparkerhenderson** [comment]
Thanks for the thanks! Good question. I don't know an answer. I'll dig this weekend, and let you know what turns up.

I'm curious in general, because I see you're an expert in robotics. What kind of things are you doing with Rust?

**Comment by bjones1** [comment]
@joelparkerhenderson, thanks! The new version works beautifully.

Sadly, my profile is a bit out of date; I no longer work in robotics, but focus quite a bit on literate programming and embedded systems. I'm using Rust for a literate programming tool I'm developing; see https://github.com/bjones1/CodeChat_Editor. I'd be happy to provide more info if you're interested.
